language: cpp
matrix:
  include:
    - name: Linux GCC 8 Debug/Coverage
      os: linux
      dist: xenial
      env: BUILD_TYPE=Debug EXTRA_CMAKE=-DCOVERAGE=On GCOV=gcov-8 MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      addons:
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
            - llvm-toolchain-xenial-7
          packages:
            - g++-8
    - name: Linux GCC 8 Release
      os: linux
      dist: xenial
      env: BUILD_TYPE=Release LTO=On MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      addons:
        apt:
          sources: *sources
          packages:
            - g++-8
    - name: Linux GCC 7 Release
      os: linux
      dist: xenial
      env: BUILD_TYPE=Release LTO=On MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources: *sources
          packages:
            - g++-7
    - name: Linux GCC 6 Release
      os: linux
      dist: xenial
      env: BUILD_TYPE=Release LTO=On MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons:
        apt:
          sources: *sources
          packages:
            - g++-6
    - name: Linux Clang 8 Release
      os: linux
      dist: xenial
      env: BUILD_TYPE=Release LTO=On MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
      addons:
        apt:
          sources: *sources
          packages:
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
    - name: Linux Clang 7 Release
      os: linux
      dist: xenial
      env: BUILD_TYPE=Release LTO=On MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
      addons:
        apt:
          sources: *sources
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
    - name: OSX GCC 9 Release
      os: osx
      osx_image: xcode10.1
      env: BUILD_TYPE=Release MATRIX_EVAL="brew link --overwrite gcc && CC=gcc-9 && CXX=g++-9"
    - name: OSX XCode 10.1 Release
      os: osx
      osx_image: xcode10.1
      env: BUILD_TYPE=Release
before_install:
    - eval "${MATRIX_EVAL}"
script:
  - mkdir out
  - cd out
  - cmake -Wno-dev -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${EXTRA_CMAKE} ..
  - cmake --build . -- -j2
  - ctest --output-on-failure -D ExperimentalBuild -j2
  - ctest --output-on-failure -D ExperimentalTest -j2
  - '[[ -z "${GCOV}" ]] || bash <(curl -s https://codecov.io/bash) -x ${GCOV}'

